### ISSUE TITLE
Meta d'un article

### ISSUE THREAD

**Issue by Alciie** [Chambe-Carnet/chambecarnet#16]
Sur les articles il faudrait afficher ou pas certains "meta" en fonction de là où on est :
- home, faire afficher la date et la catégorie
- liste catégories, faire afficher la date
- détail article, faire afficher la date et l'auteur (pour l’auteur pas besoin de sa photo)

Question : est-ce pertinent de rendre les éléments cliquables ?

**Comment by jihaisse** [comment]
fixed by #23
