### ISSUE TITLE
Load more sur Home Page

### ISSUE THREAD

**Issue by jihaisse** [Chambe-Carnet/chambecarnet#46]
Faire en sorte de charger plus de billets au clic sur la home.

**Comment by crazy-seb** [comment]
J'ai mis en place le 'load more' sur l'accueil. 
Il faudrait faire le style et peut être modifier le js pour afficher un gif pendant le chargement des posts plutôt que de simplement changer le texte du bouton.

**Comment by jihaisse** [comment]
cf #65
