### ISSUE TITLE
Affichage des jobs

### ISSUE THREAD

**Issue by crazy-seb** [Chambe-Carnet/chambecarnet#54]
Est-ce normal que l'affichage individuel des offres d’emplois soit différent si on passe par l'accueil ou par le menu du header ?

**Comment by jihaisse** [comment]
Sur la home, dans la liste des billets, il y a des billets dans la catégorie "jobs", ce sont des billets écrits à la main qui reprennent des offres d'emploi. C'est juste un billet, donc différent d'une offre d'emploi du job board.
